version: '3.7'

services:
  sdk-api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DB_HOST: db
    #container_name: 'sdk-api'
    restart: 'always' #on-failure
    #depends_on:
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - api_network
      - postgres_network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sdk.entrypoints=websecure"
      - "traefik.http.routers.sdk.rule=Host(`sdk-api.minorfoodit.com`)"
      - "traefik.http.routers.sdk.service=sdk-api"
      - "traefik.http.routers.sdk-api.tls=true"
      - "traefik.http.services.sdk-api.loadbalancer.server.port=2020"
      - "traefik.docker.network=api_network"

networks:
  postgres_network:
    external: true
  api_network:
    external: true